In [1]:
import numpy as np

In [11]:
class AddBorderInside:
    def addBorderInside(self):
        original = np.ones((5,5))
        print("original",original)
        original[0,:] = original[:,0] =  original[:,-1] = original[-1,:] = 0
        print("modified",original)

if __name__ == "__main__":
    addborder = AddBorderInside()
    addborder.addBorderInside()

original [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
modified [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
